app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 864000000
spring:
  data:
    mongodb:
      uri: mongodb://longpc:longpc%40mongo@mongodb:27017/quiz?authSource=admin

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
server:
  servlet:
    context-path: /tuto-backend
  port: 8099
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

